version: '3'
services:
  mysqlvs:
    build:
      context: .
      dockerfile: mysql.df
    image: lalosam/mysql-vs:1.0
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
      - "33060:33060"
    container_name: mysqlvs
    healthcheck:
      test: "mysql -u root -p$MYSQL_ROOT_PASSWORD -e \"select 1 from dual;\""
      interval: 2s
      retries: 100
  intouch:
    depends_on:
      - mysqlvs
    image: lalosam/intouch:latest
    external_links:
      - mysqlvs:mysqlvs
    ports:
      - "9090:9090"
    container_name: intouch

